import localFont from "next/font/local";
import "./globals.css";
import Sidebar from '../components/sidebar';
import TopBar from '../components/topbar';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <div className="flex flex-col flex-grow h-screen">
            <TopBar />
            <main className="flex-grow overflow-y-auto p-4 bg-gray-50 h-[90%] font-inter">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
